"""
Pytest configuration for notebook tests.

Cleans up any files generated by notebooks during the test run so that
running `pytest` locally does not leave output artefacts in the repository.
"""
import pathlib


def _notebook_docs_files():
    return {
        p
        for d in pathlib.Path("schemas").rglob("docs")
        for p in d.iterdir()
        if p.is_file()
    }


_files_before_test = set()


def pytest_runtest_setup(item):
    global _files_before_test
    _files_before_test = _notebook_docs_files()


def pytest_runtest_teardown(item, nextitem):
    for new_file in _notebook_docs_files() - _files_before_test:
        new_file.unlink(missing_ok=True)
