#!/usr/bin/env python3
"""
convert_to_json.py: convert all schema.oold.yaml files to schema.oold.json.

Scans every schema.oold.yaml under schemas/ and writes a JSON equivalent
alongside it as schema.oold.json.  YAML comments and anchors are stripped;
all other structure is preserved exactly.

Each generated file includes an x-generated-from field so editors know
to modify schema.oold.yaml instead.

JSON-LD processors and downstream tooling can reference the .json sibling
instead of the .yaml source when they cannot consume YAML directly.

Usage:
    python scripts/convert_to_json.py           # convert all schemas
    python scripts/convert_to_json.py --check   # exit non-zero if any JSON is stale
    python scripts/convert_to_json.py --clean   # delete all generated JSON files
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"

GENERATED_FROM_KEY = "x-generated-from"
GENERATED_FROM_VALUE = "schema.oold.yaml — do not edit this file directly"


def annotated(data: dict) -> dict:
    """Return data with x-generated-from inserted as the first key."""
    return {GENERATED_FROM_KEY: GENERATED_FROM_VALUE, **data}


def main() -> None:
    check_mode = "--check" in sys.argv
    clean_mode = "--clean" in sys.argv

    yaml_paths = sorted(SCHEMAS_DIR.rglob("*/specs/schema.oold.yaml"))

    if clean_mode:
        removed = 0
        for yaml_path in yaml_paths:
            json_path = yaml_path.with_name("schema.oold.generated.json")
            if json_path.exists():
                json_path.unlink()
                removed += 1
        print(f"Removed {removed} JSON file(s).")
        return

    stale: list[str] = []
    converted = 0

    for yaml_path in yaml_paths:
        data = annotated(yaml.safe_load(yaml_path.read_text()))
        json_output = json.dumps(data, indent=2) + "\n"
        json_path = yaml_path.with_name("schema.oold.generated.json")

        if check_mode:
            current = json_path.read_text() if json_path.exists() else ""
            if current != json_output:
                stale.append(str(json_path.relative_to(REPO_ROOT)))
        else:
            json_path.write_text(json_output)
            converted += 1

    if check_mode:
        if stale:
            print(f"{len(stale)} JSON file(s) are out of date:", file=sys.stderr)
            for p in stale:
                print(f"  {p}", file=sys.stderr)
            print(
                "Run  python scripts/convert_to_json.py  to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
        else:
            print("All schema.oold.json files are up-to-date.")
    else:
        print(f"Converted {converted} schema(s).")


if __name__ == "__main__":
    main()
