#!/usr/bin/env python3
"""
convert_to_json.py: convert all schema.oold.yaml files to schema.oold.generated.json.

Scans every schema.oold.yaml under schemas/ and writes a JSON equivalent
alongside it as schema.oold.generated.json.  YAML comments and anchors are stripped;
all other structure is preserved exactly, with one enhancement:

  @context merging
  ----------------
  When a schema declares ``allOf: [{$ref: ...}]``, the @context of each
  referenced schema is deep-merged into the output @context **before** the
  child's own entries.  Child entries always win on conflict.  This mirrors
  how resolveSchemaRefs() already handles properties, and removes the need
  for manual ``# mirrored from …`` sections in child schemas.

  Merging is transitive: if A extends B which extends C, A's generated JSON
  carries the union of all three contexts.

Each generated file includes an x-generated-from field so editors know
to modify schema.oold.yaml instead.

Usage:
    python scripts/convert_to_json.py           # convert all schemas
    python scripts/convert_to_json.py --check   # exit non-zero if any JSON is stale
    python scripts/convert_to_json.py --clean   # delete all generated JSON files
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMAS_DIR = REPO_ROOT / "schemas"

GENERATED_FROM_KEY = "x-generated-from"
GENERATED_FROM_VALUE = "schema.oold.yaml — do not edit this file directly"


def _merge_contexts(base: dict, child: dict) -> dict:
    """Return a merged @context dict; child entries override base entries."""
    return {**base, **child}


def _resolve_context(yaml_path: Path, visited: frozenset[Path] | None = None) -> dict:
    """
    Load a schema YAML and return the @context that would be used at runtime:
    the transitive union of all allOf $ref contexts, with child entries winning.
    """
    if visited is None:
        visited = frozenset()

    data = yaml.safe_load(yaml_path.read_text())
    own_ctx: dict = data.get("@context", {})

    allof = data.get("allOf", [])
    if not allof:
        return own_ctx

    base_ctx: dict = {}
    for entry in allof:
        ref_str = entry.get("$ref")
        if not ref_str:
            continue
        ref_path = (yaml_path.parent / ref_str).resolve()
        if ref_path in visited:
            continue
        ref_ctx = _resolve_context(ref_path, visited | {yaml_path.resolve()})
        base_ctx = _merge_contexts(base_ctx, ref_ctx)

    # Child wins over base
    return _merge_contexts(base_ctx, own_ctx)


def load_with_merged_context(yaml_path: Path) -> dict:
    """
    Load a schema YAML and replace its @context with the fully merged version
    (own entries + all inherited entries from allOf $ref targets).
    """
    data = yaml.safe_load(yaml_path.read_text())
    merged_ctx = _resolve_context(yaml_path)
    return {**data, "@context": merged_ctx}


def annotated(data: dict) -> dict:
    """Return data with x-generated-from inserted as the first key."""
    return {GENERATED_FROM_KEY: GENERATED_FROM_VALUE, **data}


def main() -> None:
    check_mode = "--check" in sys.argv
    clean_mode = "--clean" in sys.argv

    yaml_paths = sorted(SCHEMAS_DIR.rglob("*/specs/schema.oold.yaml"))

    if clean_mode:
        removed = 0
        for yaml_path in yaml_paths:
            json_path = yaml_path.with_name("schema.oold.generated.json")
            if json_path.exists():
                json_path.unlink()
                removed += 1
        print(f"Removed {removed} JSON file(s).")
        return

    stale: list[str] = []
    converted = 0

    for yaml_path in yaml_paths:
        data = annotated(load_with_merged_context(yaml_path))
        json_output = json.dumps(data, indent=2) + "\n"
        json_path = yaml_path.with_name("schema.oold.generated.json")

        if check_mode:
            current = json_path.read_text() if json_path.exists() else ""
            if current != json_output:
                stale.append(str(json_path.relative_to(REPO_ROOT)))
        else:
            json_path.write_text(json_output)
            converted += 1

    if check_mode:
        if stale:
            print(f"{len(stale)} JSON file(s) are out of date:", file=sys.stderr)
            for p in stale:
                print(f"  {p}", file=sys.stderr)
            print(
                "Run  python scripts/convert_to_json.py  to regenerate.",
                file=sys.stderr,
            )
            sys.exit(1)
        else:
            print("All schema.oold.generated.json files are up-to-date.")
    else:
        print(f"Converted {converted} schema(s).")


if __name__ == "__main__":
    main()
